title: James Riback
remote_theme: andreondra/jekyll-theme-simplex/
author: jryebread
email: jriback144@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a life long computer science student struggles with programming and rambles about VR, Science Fiction, Distributed systems, and more!

# social links
twitter_username: jamesryebread # DO NOT include the @ character, or else the build will fail!
github_username:  jryebread # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect